(()=>{'use strict';
const D=globalThis.WORKSHOP_DOMAIN_RUNS,$=id=>document.getElementById(id),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),num=n=>Number(n).toLocaleString();
const names={base:'Common base · 1,000 updates',biology:'Biology · 500 updates',email:'Email · 500 updates',finance:'Finance · 500 updates',qa:'Authored Q&A exercise · 500 updates'};
const taskNames={prose:'prose continuation',email:'instruction → email',qa:'question → answer'};
let online=false,busy=false,requestVersion=0;
function pieces(text,kind){
  text=text.toLowerCase();
  // Same splitting rule as domains/data.py; whole words, digits and punctuation.
  return kind==='character'?Array.from(text):(text.match(/[\p{L}\p{Nl}\p{No}]+(?:['’-][\p{L}\p{Nl}\p{No}]+)*|\p{Nd}|[^\p{L}\p{N}_\s]/gu)||[]);
}
function inputCheck(){
  const r=run(),text=serialized($('domain-task').value,$('domain-input').value,$('domain-incoming').value);
  const tokens=pieces(text,r.id),vocab=new Set(r.manifest.tokenizer.vocabulary);
  return {text,count:tokens.length+1,unknown:[...new Set(tokens.filter(t=>!vocab.has(t)))].sort(),context:r.manifest.config.block_size};
}
function identity(){return (run().id==='word'?'Words':'Characters')+' · '+names[chosen()];}
function explainOutput(result){
  const count=result.ids.filter(i=>i!==0&&i!==1).length;
  $('output-explanation').textContent=!/[\p{L}\p{N}]/u.test(result.text)
    ? 'The model produced no words or numbers'+(result.stop==='end token'?' and selected EOS (the end token).':'.')+' This is the actual prediction, not a useful answer or a connection error. The format and training examples above help explain this failure.'
    : count+' generated tokens · '+result.stop+'. This is an unedited continuation, not a checked answer. A familiar-looking answer may still ignore the question.';
}
$('domain-kind').innerHTML=D.runs.map(r=>`<option value="${r.id}">${r.id==='word'?'Words + digits + punctuation':'Characters'}</option>`).join('');
$('domain-stage').innerHTML=Object.entries(names).map(([k,v])=>`<option value="${k}">${v}</option>`).join('');
const params=new URLSearchParams(location.search);$('domain-stage').value=names[params.get('domain')]?params.get('domain'):'biology';if(params.get('kind')==='character')$('domain-kind').value='character';
const run=()=>D.runs.find(r=>r.id===$('domain-kind').value),stage=()=>run().stages.find(s=>s.name===$('domain-stage').value),chosen=()=>$('domain-inspect').value==='base'?'base':stage().name;
function serialized(task,text,incoming=''){return task==='qa'?'question: '+text.trim()+'\nanswer: ':task==='email'?'### instruction:\n'+text+(incoming?'\n\n### incoming email:\n'+incoming:'')+'\n\n### email:\n':text;}
function chart(s){const h=s.history,max=Math.ceil(Math.max(...h.flatMap(p=>[p.validation,p.base_validation,p.train_batch||0]))),x=v=>45+v/s.steps*680,y=v=>205-v/max*155;return `<svg viewBox="0 0 780 255" role="img" aria-label="Target-domain validation and base-corpus validation over ${s.steps} updates"><text x="45" y="20" font-size="13" fill="#087e70">Branch validation</text><text x="270" y="20" font-size="13" fill="#a25225">Base-corpus validation</text>${[0,.5,1].map(t=>`<line x1="45" x2="725" y1="${y(t*max)}" y2="${y(t*max)}" stroke="#ddd"/><text x="10" y="${y(t*max)+4}" font-size="12">${(t*max).toFixed(1)}</text>`).join('')}${[['validation','#087e70'],['base_validation','#a25225']].map(([key,c])=>`<polyline points="${h.map(p=>`${x(p.step)},${y(p[key])}`).join(' ')}" fill="none" stroke="${c}" stroke-width="3"/>`).join('')}<text x="45" y="232" font-size="12">0 updates</text><text x="630" y="232" font-size="12">${s.steps} updates</text><text x="200" y="251" font-size="12">Cross-entropy per scored target token (nats); lower is better</text></svg>`;}
function invalidate(){requestVersion++;$('domain-error').hidden=true;$('output-explanation').textContent='';$('output-label').textContent='INPUT OR CHECKPOINT CHANGED';$('domain-output').textContent='Generate to see this input with the selected weights.';showInput();}
function showInput(){
  const r=run(),trained=r.stages.find(s=>s.name===chosen()),task=$('domain-task').value,check=inputCheck();
  $('serialized-input').textContent=check.text;
  $('input-model').textContent='Selected weights: '+identity()+'. Trained task: '+taskNames[trained.task]+'. Input format changes the prompt layout only; it does not select or train a model.';
  $('incoming-wrap').hidden=task!=='email';
  $('task-warning').hidden=trained.task===task;
  $('task-warning-text').textContent='Format mismatch: these weights practised '+taskNames[trained.task]+', but this input uses '+taskNames[task]+'. You can generate to observe the mismatch. Do not expect a reliable '+(task==='qa'?'answer':task==='email'?'email':'continuation')+'.';
  $('use-task-branch').hidden=task==='prose';
  $('use-task-branch').textContent='Use '+(task==='qa'?'Q&A':'Email')+' weights · keep input';
  $('task-description').textContent=task==='qa'
    ? 'For the practiced question, choose the Authored Q&A branch and try “what is a cat?”. “Where is the cat?” asks for a location that this exercise was not given. Even the Q&A model may return a memorized definition instead.'
    : task==='email'
    ? 'Choose the Email branch for instructions and replies. Its 500 updates teach narrow email patterns; it is not a general email assistant. An accepted input can still produce an incoherent or irrelevant email.'
    : 'Use an unfinished sentence to inspect prose continuation. Biology and Finance learned prose, not instructions or question answering. Use the branch example for a reproducible comparison.';
  $('vocabulary-check').hidden=!check.unknown.length;
  $('vocabulary-message').textContent='Outside this checkpoint vocabulary: '+check.unknown.slice(0,12).join(', ')+(check.unknown.length>12?' …':'')+'. '+(r.id==='word'?'These word pieces have no IDs in any of the word branches. Switching to Email or Q&A does not add them. Try the character checkpoint with the same text, or replace the input with the branch example. Character weights are a separate model and do not guarantee a good answer.':'These characters have no IDs. Edit them or use the branch example.');
  $('use-characters').hidden=r.id!=='word';
  $('input-status').textContent=check.count+' input tokens including BOS / '+check.context+' context positions. '+(check.count>=check.context?'Shorten the input to leave room for generation.':check.unknown.length?'Generation requires known pieces; no words will be silently discarded.':'All input pieces have IDs. This does not mean the model knows how to answer.');
}
function example(){requestVersion++;const s=stage();$('domain-task').value=s.task;$('domain-input').value=s.example_input;$('domain-incoming').value='';showInput();$('domain-error').hidden=true;if(chosen()===s.name){$('output-label').textContent='SAVED GREEDY PREVIEW · '+identity();$('domain-output').textContent=s.sample.text||'(No visible text before the end token.)';explainOutput(s.sample);}else invalidate();}
function render(resetInput=true){const r=run(),s=stage(),m=r.manifest,sp=m.splits[s.name],first=s.history[0],last=s.history.at(-1);requestVersion++;
$('domain-specs').innerHTML=`<p class="method-note"><b>Currently inspecting:</b> ${esc(names[chosen()])} · ${esc(r.id)} TinyGPT.<br><b>Lineage:</b> random initialization → common base trained for 1,000 updates → ${s.name==='base'?'no adaptation selected':esc(s.name)+' fine-tuned independently for '+s.steps+' updates'}. ${s.name!=='base'?'Every branch starts from the same base.pt. These are full-weight updates, not LoRA.':''}</p><p><b>Base data:</b> 432 controlled classroom sentences + 3 short stories. The base never trained on the external domain examples. Its vocabulary was planned using all training splits.</p><p><b>This branch:</b> ${num(sp.train.records)} training / ${num(sp.validation.records)} validation records. ${esc(s.method)}; batch ${s.batch_size}; learning rate ${s.learning_rate}; ${s.steps} updates; ${s.seconds.toFixed(1)} s recorded on ${esc(r.device_name)}.</p><p class="subtle">${num(r.parameter_count)} parameters · ${num(m.config.vocab_size)} vocabulary entries · ${m.config.block_size} context positions · 2 blocks / 2 heads / 64 features. Sampling training records with replacement; 500 updates is not 500 epochs or 500 unique records. Timing includes evaluation/plots, excludes startup and final save/generation.</p><p class="subtle">This branch’s validation contains ${sp.validation.unknown_tokens} UNK input tokens. The base-corpus probe for this tokenization contains ${m.splits.base.validation.unknown_tokens}; those unseen pieces map to UNK without changing the vocabulary.</p><p><b>Branch validation:</b> ${first.validation.toFixed(3)} → ${last.validation.toFixed(3)}. <b>Base validation:</b> ${first.base_validation.toFixed(3)} → ${last.base_validation.toFixed(3)}.</p><p class="subtle">The historical curves stay fixed when you inspect base/after. Validation uses all scored held-out targets. Email/Q&A score response tokens only; prose scores every next token. Loss is not accuracy; avoid cross-task or cross-tokenizer comparisons. Shared templates can cross splits. Fixed update budgets; no final test set.</p><details><summary>Checkpoint identity and exact settings</summary><p><code>${esc(r.path)}/${chosen()}.pt</code></p><p class="hash">Base SHA-256: ${esc(r.stages[0].sha256)}</p><a href="../../${r.path}/report.json">Complete report</a> · <a href="../../${r.path}/data_manifest.json">Data manifest</a> · <a href="../../${r.path}/${s.name}_progress.png">Python plot</a></details>`;
$('domain-curve').innerHTML=chart(s);
$('preparation-steps').innerHTML=`<ol>${m.pipeline.map(x=>`<li>${esc(x)}</li>`).join('')}</ol><p><b>${s.name==='email'?'Email fields: instruction + optional incoming_email form the prompt; email is the target. The redundant text column is not concatenated again. Its textual end marker is replaced with our EOS token.':s.name==='qa'?'Q&A: explicitly authored examples, separate from the supplied CSVs. Holdout changes the phrasing, not the concepts.':'Prose: the text field is input and supplies next-token targets. IDs/categories are metadata.'}</b></p><p>${esc(m.split_caution)}</p><details><summary>Source file and raw example</summary><pre class="code">${esc(JSON.stringify(m.sources[s.name],null,2))}</pre></details>`;
$('domain-vocabulary').innerHTML=`<p>Vocabulary is the list of allowed token pieces and their integer IDs. Here the designer chose ${r.id==='word'?'lowercase whole words, individual digits and punctuation':'lowercase characters'}, then collected the distinct pieces from the planned training data and added BOS, EOS and UNK. That produced <b>${m.config.vocab_size} entries</b>. A larger training corpus can produce a different size. Context length (${m.config.block_size}) is a separate architecture choice.</p><p>${esc(m.vocabulary_scope)} The mapping stays fixed through all five stages. New prompts do not add entries. Production subword tokenizers often fit pieces toward a chosen vocabulary budget instead.</p><details><summary>See all IDs</summary><p class="hash">${m.tokenizer.vocabulary.map((v,i)=>`${i}: ${esc(v)}`).join(' · ')}</p></details>`;
$('prepared-search').value='';records();if(resetInput)example();else showInput();}
function records(){const rows=run().records[stage().name][$('prepared-split').value],q=$('prepared-search').value.toLowerCase(),matches=rows.filter(r=>r.sentence.toLowerCase().includes(q));$('prepared-count').textContent=`${matches.length} matching records out of ${rows.length}; showing up to 100 choices.`;$('prepared-record').innerHTML=matches.slice(0,100).map(r=>`<option value="${esc(r.id)}">${esc(r.id)} · ${esc(r.category)}</option>`).join('');record();}
function record(){const r=run().records[stage().name][$('prepared-split').value].find(r=>r.id===$('prepared-record').value);if(!r){$('prepared-view').textContent='No matching records.';return;}const prefix=r.task==='prose'?'':serialized(r.task,r.instruction,r.incoming_email||'');$('prepared-view').innerHTML=`<p>ID ${esc(r.id)} · ${esc(r.category)} · ${esc($('prepared-split').value)}</p>${prefix?`<strong>Prompt · input only, loss masked</strong><pre class="code">${esc(prefix)}</pre>`:''}<strong>${prefix?'Response · scored learning targets':'Prose · all next-token targets scored'}</strong><pre class="code">${esc(r.response)}</pre><p class="subtle">BOS begins the input, EOS is a scored end target. Input IDs are shifted by one position to form targets. Padding uses ignored targets; records are never silently truncated. ${prefix?'Prompt tokens are visible through attention but have target label −100, so the loss trains the response.':''}</p>`;}
$('domain-stage').onchange=()=>render();
$('domain-kind').onchange=()=>{render(false);invalidate();};
$('use-task-branch').onclick=()=>{const task=$('domain-task').value;if(task!=='email'&&task!=='qa')return;$('domain-stage').value=task;$('domain-inspect').value='after';render(false);invalidate();};
$('use-characters').onclick=()=>{$('domain-kind').value='character';render(false);invalidate();};
$('domain-inspect').onchange=()=>{render(false);invalidate();};$('domain-example').onclick=example;
for(const id of ['domain-input','domain-incoming','domain-task','domain-budget'])$(id).addEventListener(id==='domain-task'?'change':'input',invalidate);
$('prepared-split').onchange=records;$('prepared-search').oninput=records;$('prepared-record').onchange=record;
$('domain-generate').onclick=async()=>{if(!online||busy)return;const check=inputCheck();if(check.unknown.length){$('domain-error').textContent='Outside this checkpoint vocabulary: '+check.unknown.slice(0,12).join(', ')+'. Use the vocabulary options above.';$('domain-error').hidden=false;$('output-label').textContent='INPUT NOT SENT';$('domain-output').textContent='No new output.';$('output-explanation').textContent='';return;}busy=true;const version=++requestVersion;$('domain-generate').disabled=true;$('domain-error').hidden=true;$('output-label').textContent='GENERATING LOCALLY · '+identity();$('domain-output').textContent='';$('output-explanation').textContent='';try{const response=await fetch('/api/workshop/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:run().id,stage:chosen(),task:$('domain-task').value,text:$('domain-input').value,incoming:$('domain-incoming').value,tokens:Number($('domain-budget').value)})});const result=await response.json();if(version!==requestVersion)return;if(!response.ok)throw Error(result.error);$('output-label').textContent=`LIVE GREEDY OUTPUT · ${identity()} · ${result.stop}`;$('domain-output').textContent=result.text||'(End token selected; no visible response.)';$('serialized-input').textContent=result.serialized_input;explainOutput(result);}catch(e){if(version===requestVersion){$('domain-error').textContent=e.message;$('domain-error').hidden=false;$('output-label').textContent='GENERATION FAILED';$('domain-output').textContent='No new output.';}}finally{busy=false;$('domain-generate').disabled=!online;}};
render();$('domain-service').textContent='Saved previews and data are available offline. Live generation needs the local Python server.';
if(location.protocol!=='file:')fetch('/api/workshop/health').then(r=>r.json()).then(r=>{if(r.service!=='llm-workshop-domain-inference')return;online=true;$('domain-generate').disabled=false;$('server-help').hidden=true;$('domain-service').textContent='Connected to local Python inference · CPU · no external API. Selecting checkpoints does not train.';}).catch(()=>{});
})();
