"""Export the shared TinyGPT to the offline browser lab; no UI calculations here.

Run from learning/llm-workshop-001: python llm_workshop/browser/export_model.py
Rebuilds bundled seed-1337 weights and a measured 200-update training comparison.
"""
from pathlib import Path
import argparse
import hashlib
import json
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
import torch
from llm_workshop.teaching import Session, topic


def weights(model):
    return {name: value.detach().cpu().tolist() for name, value in model.named_parameters()}


def reference(session, name, text):
    """Full selected-block intermediates, checked by topic 003 against Block.forward."""
    traces = []
    for block in range(session.model.cfg.n_layer):
        traces.append([topic(3).inspect(session, text, block, head)
                       for head in range(session.model.cfg.n_head)])
    with torch.inference_mode():
        logits = session.model(session.ids(text))[0][0].tolist()
    def clean(value):
        if isinstance(value, torch.Tensor):
            return clean(value.tolist())
        if isinstance(value, list):
            return [clean(v) for v in value]
        if isinstance(value, dict):
            return {k: clean(v) for k, v in value.items()}
        if isinstance(value, float) and not torch.isfinite(torch.tensor(value)):
            return None  # JS test restores masked negative infinity.
        return value
    return {'model': name, 'text': text, 'logits': logits, 'blocks': clean(traces),
            'embeddings': clean(topic(2).inspect(session, text))}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output', type=Path, default=Path(__file__).parent / 'model-data.js')
    parser.add_argument('--references', type=Path, help='Optional PyTorch fixtures for the JS equivalence test')
    args = parser.parse_args()
    session = Session()
    data = {'config': session.model.cfg.__dict__, 'vocabulary': session.vocabulary,
            'seed': session.seed, 'models': {'untrained': {'step': 0, 'weights': weights(session.model)}}}
    references = [reference(session, 'untrained', text) for text in ('the cat sat.', 'aaa', 'a')] if args.references else []
    run = topic(4).TrainingRun(session)
    for _ in range(200):
        run.advance()
    data['models']['trained'] = {'step': run.step, 'weights': weights(session.model)}
    data['training'] = {'history': run.history, 'samples': run.sample_pair(),
                        'learning_rate': run.learning_rate, 'batch_size': 4,
                        'context': run.block, 'optimizer': 'AdamW', 'torch_version': torch.__version__,
                        'data_hashes': {key: hashlib.sha256(text.encode()).hexdigest() for key, text in run.texts.items()},
                        'source': 'llm_workshop/004_training_from_scratch/demo.py'}
    data['parameter_count'] = sum(p.numel() for p in session.model.parameters())
    args.output.write_text('// Generated by export_model.py; measured model parameters, not illustrative data.\n'
                           + 'globalThis.WORKSHOP_MODEL = ' + json.dumps(data, separators=(',', ':'), allow_nan=False) + ';\n', encoding='utf-8')
    if args.references:
        references += [reference(session, 'trained', text) for text in ('the cat sat.', 'aaa', 'a')]
        args.references.write_text(json.dumps(references, allow_nan=False), encoding='utf-8')
    print(f'Exported {data["parameter_count"]:,} parameters per model to {args.output}')
    print('Measured loss:', run.history[0], '→', run.history[-1])


if __name__ == '__main__':
    main()
