/* Run: node llm_workshop/browser/test_engine.cjs /tmp/llm-browser-reference.json
   Fixtures are generated from PyTorch by export_model.py --references PATH. */
const assert = require('node:assert/strict');
const fs = require('node:fs');
require('./model-data.js');
const E = require('./engine.js');
const data = globalThis.WORKSHOP_MODEL;
assert(process.argv[2], 'Supply the PyTorch reference JSON generated by export_model.py.');
const fixtures = JSON.parse(fs.readFileSync(process.argv[2], 'utf8'));
let maxError = 0, comparisons = 0;
function compare(actual, expected, name) {
  if (Array.isArray(expected)) {
    assert.equal(actual.length, expected.length, `${name}: dimension`);
    expected.forEach((v,i)=>compare(actual[i],v,`${name}[${i}]`));
  } else if (expected === null) {
    assert.equal(actual, -Infinity, `${name}: masked cell`);
  } else {
    const error = Math.abs(Number(actual) - Number(expected));
    maxError = Math.max(maxError,error);
    assert(error <= 3e-5 + Math.abs(Number(expected))*1e-5, `${name}: ${actual} vs ${expected}, error ${error}`);
    comparisons++;
  }
}
for (const fixture of fixtures) {
  const ids=E.encode(fixture.text,data.vocabulary,data.config.block_size);
  const trace=E.forward(ids,data.models[fixture.model],data.config);
  compare(trace.logits,fixture.logits,`${fixture.model} ${fixture.text} logits`);
  for (const key of ['tokens','positions','combined']) compare(trace[key],fixture.embeddings[key],key);
  fixture.blocks.forEach((heads,bi)=>heads.forEach((expected,hi)=>{
    for(const key of Object.keys(expected)) {
      const actual = trace.blocks[bi].heads[hi][key] || trace.blocks[bi][key];
      compare(actual,expected[key],`${fixture.model}, block ${bi}, head ${hi}, ${key}`);
    }
  }));
}
for (const name of ['untrained','trained']) {
  const model=data.models[name];
  const first=E.forward(E.encode('the cat',data.vocabulary,64),model,data.config);
  const second=E.forward(E.encode('the dog',data.vocabulary,64),model,data.config);
  compare(first.logits.slice(0,4),second.logits.slice(0,4), 'Future-token causality');
  for(const block of first.blocks) for(const head of block.heads) head.attention.forEach((row,i)=>{
    assert(Math.abs(row.reduce((a,b)=>a+b,0)-1)<1e-12);
    assert(row.slice(i+1).every(v=>v===0));
  });
  const long=E.forward(Array(64).fill(data.vocabulary.indexOf('a')),model,data.config);
  assert(long.logits.flat().every(Number.isFinite));
}
assert.throws(()=>E.encode('',data.vocabulary,64));
assert.throws(()=>E.encode('🦉',data.vocabulary,64));
assert.throws(()=>E.encode('a'.repeat(65),data.vocabulary,64));
assert.throws(()=>E.forward([-1],data.models.untrained,data.config));
assert.throws(()=>E.softmax([1,2],0));
compare(E.softmax([0,Math.log(2),-Infinity]),[1/3,2/3,0],'Hand-worked softmax');
assert.equal(E.choose([.1,.8,.1],true),1);
assert.equal(E.choose([.1,.8,.1],false,()=>.95),2);
const context=[0,data.vocabulary.indexOf('a')];
assert(E.forward(context,data.models.trained,data.config).logits.flat().every(Number.isFinite),'Reserved token stays a valid ID.');
const evidence=E.retrieve('Where is the Neral instrument?', ['The Neral instrument is in K142.','The library is open.']);
assert.equal(evidence[0].index,0);
assert.equal(E.retrieve('xyzzy', ['The library is open.'])[0].score,0);
console.log(`PASS: ${comparisons.toLocaleString()} scalar comparisons with PyTorch; maximum absolute error ${maxError.toExponential(3)}. Causality, masks, 64-token contexts, invalid inputs, sampling, reserved IDs and retrieval passed.`);
